<script lang="ts">
  import { trainerAction } from './gateway';
  let { practice=false,onClose }=$props<{practice?:boolean;onClose:()=>void}>();
  let seed=$state('');let context=$state('');let busy=$state(false);let error=$state('');let stage=$state('等待填写教学目标');let progress=$state(0);let pendingId=$state('');let result=$state<Record<string,unknown>|null>(null);let approved=$state(false);
  async function generate(){if(seed.trim().length<40){error='请至少填写 40 个字符，包含现有基础、学习目标和期望作品。';return}busy=true;error='';stage='正在创建候选教学结构…';progress=15;try{const job=await trainerAction<{id:string}>('candidate-generate',{seed:seed.trim(),language:'由 Trainer 识别',projectContext:context.trim(),generationMode:practice?'project-practice':'course'});for(let i=0;i<180;i++){await new Promise(r=>setTimeout(r,1000));const next=await trainerAction<Record<string,unknown>>('job',{id:job.id});stage=String(next.message??'正在生成并验证候选 Skill…');progress=Number(next.total)?Math.max(15,Math.min(92,Number(next.completed??0)/Number(next.total)*90)):Math.min(90,progress+2);if(next.status==='completed'){result=next.result as Record<string,unknown>;const pending=(result?.pending??{}) as Record<string,unknown>;pendingId=String(pending.pendingId??'');progress=100;stage='候选教学已生成并通过结构检查';return}if(['failed','paused','cancelled'].includes(String(next.status)))throw new Error(String(next.error??'生成任务未完成'));}throw new Error('生成仍在进行，可在生成任务中继续查看。')}catch(e){error=e instanceof Error?e.message:String(e)}finally{busy=false}}
  async function approve(){if(!pendingId)return;busy=true;error='';try{await trainerAction('pending-approve',{id:pendingId});approved=true;stage='已审批并写入 Skill 知识库'}catch(e){error=e instanceof Error?e.message:String(e)}finally{busy=false}}
</script>
<div class="modal-backdrop"><section class="builder-window"><header><div><h1>{practice?'项目实战 · 从目标到可运行项目':'创建课程 Skill'}</h1><p>生成内容先进入候选区；通过验证并由你审批后才写入知识库。</p></div><button class="close-button" onclick={onClose}>完成</button></header>
  <label class="builder-field"><strong>教学需求</strong><textarea bind:value={seed} rows="6" placeholder="描述想学的技术、现有基础、目标作品和学习要求；也可粘贴参考资料…"></textarea><small>{seed.trim().length} / 至少 40 字</small></label>
  <label class="builder-field"><strong>项目语境（可选）</strong><input bind:value={context} placeholder="操作系统、IDE、现有项目或限制条件"/></label>
  <button class="primary" onclick={generate} disabled={busy||approved}>{busy?'正在生成…':'✦ 生成并验证候选 Skill'}</button>
  <div class="generation-stage"><div class="stage-head"><strong>{stage}</strong><span>{Math.round(progress)}%</span></div><progress max="100" value={progress}></progress><div class="stage-steps"><span class:done={progress>=15}>1 建立教学边界</span><span class:done={progress>=45}>2 设计课程结构</span><span class:done={progress>=75}>3 校验练习一致性</span><span class:done={progress===100}>4 等待人工审批</span></div></div>
  {#if result}<section class="candidate-card"><span class="badge">候选教学</span><h2>{String(((result.draft??{}) as Record<string,unknown>).title??'新课程 Skill')}</h2><p>{String(((result.draft??{}) as Record<string,unknown>).summary??'')}</p>{#if !approved}<button class="primary" onclick={approve} disabled={busy||!pendingId}>✓ 审批并写入知识库</button>{:else}<div class="answer-feedback">已保存。回到教学入口选择此 Skill 生成课程。</div>{/if}</section>{/if}
  {#if error}<div class="inline-error">{error}</div>{/if}
</section></div>
<style>
  .builder-window{width:min(760px,94vw);max-height:92vh;overflow:auto;background:#211e24;border:1px solid #ffffff22;border-radius:22px;padding:28px;box-shadow:0 35px 120px #000b}.builder-window>header{display:flex;justify-content:space-between;gap:20px}.builder-window h1{font-size:24px;margin:0}.builder-window header p{color:#a8a5b0;margin:7px 0 22px}.builder-field{display:grid;gap:8px;margin:14px 0}.builder-field strong{font-size:13px}.builder-field small{color:#a8a5b0;text-align:right}.builder-field textarea,.builder-field input{background:#18161c;border:1px solid #ffffff1c;border-radius:11px;padding:13px;resize:vertical}.generation-stage{margin:20px 0;padding:17px;border-radius:13px;background:#ffffff0f}.stage-head{display:flex;justify-content:space-between}.generation-stage progress{width:100%;height:7px;margin:13px 0;accent-color:#7560ff}.stage-steps{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;font-size:10px;color:#a8a5b0}.stage-steps span.done{color:#69dd89}.candidate-card{border:1px solid #7761ff4d;background:#6a55c31a;border-radius:14px;padding:18px}.candidate-card h2{margin:10px 0 6px}.candidate-card p{color:#a8a5b0}.badge{display:inline-block;border-radius:999px;padding:4px 8px;background:#6f5bff30;color:#b8acff;font-size:10px}
</style>
