<script lang="ts">
  import { onMount } from 'svelte';import { trainerAction } from './gateway';
  type Pending={pendingId:string;source:string;createdAt:string;title:string;skillId:string;valid:boolean};
  let {onClose}=$props<{onClose:()=>void}>();let items=$state<Pending[]>([]);let selected=$state<Pending|null>(null);let record=$state<Record<string,unknown>|null>(null);let loading=$state(true);let busy=$state(false);let error=$state('');
  const message=(e:unknown)=>e instanceof Error?e.message:String(e);
  async function load(){loading=true;try{const v=await trainerAction<{candidates:Pending[]}>('pending');items=v.candidates??[];if(items.length)await choose(items[0]);else selected=null}catch(e){error=message(e)}finally{loading=false}}
  async function choose(item:Pending){selected=item;record=null;try{record=await trainerAction('pending-detail',{id:item.pendingId})}catch(e){error=message(e)}}
  async function action(kind:'pending-approve'|'pending-discard'){if(!selected)return;busy=true;error='';try{await trainerAction(kind,{id:selected.pendingId});await load()}catch(e){error=message(e)}finally{busy=false}}
  function draft(){const result=record?.result as Record<string,unknown>|undefined;return (result?.draft??{}) as Record<string,unknown>}
  onMount(load);
</script>
<div class="modal-backdrop" onclick={(e)=>{if(e.target===e.currentTarget)onClose()}} role="presentation"><div class="approval-window modal-enter" role="dialog" aria-modal="true"><header class="library-header"><div><span class="eyebrow">REVIEW QUEUE</span><h1>候选教学审批</h1><p>AI 生成内容不会自动进入知识库；在这里核对结构、来源与安全边界。</p></div><button class="close-button" onclick={onClose}>完成</button></header>{#if error}<div class="notice">{error}</div>{/if}<div class="approval-body"><aside class="pending-list">{#if loading}<div class="skeleton-stack"><i></i><i></i><i></i></div>{/if}{#each items as item}<button class:active={selected?.pendingId===item.pendingId} onclick={()=>choose(item)}><span class:valid={item.valid}>{item.valid?'✓':'!'}</span><div><strong>{item.title}</strong><small>{item.source} · {new Date(item.createdAt).toLocaleString()}</small></div></button>{:else}{#if !loading}<div class="empty-compact">暂无待审批内容</div>{/if}{/each}</aside><main class="pending-review">{#if selected}<div class="skill-title"><div><span class="badge">候选 Skill</span><h2>{String(draft().title??selected.title)}</h2><p>{String(draft().id??selected.skillId)}</p></div></div><div class="review-grid"><div><span>结构校验</span><strong class:good={selected.valid}>{selected.valid?'已通过':'未通过'}</strong></div><div><span>生成来源</span><strong>{selected.source}</strong></div></div><article class="document-preview"><h3>候选说明</h3><p>{String(draft().summary??draft().description??'此候选未提供摘要，请检查教学文档后再决定。')}</p></article><div class="review-actions"><button class="danger" onclick={()=>action('pending-discard')} disabled={busy}>驳回并丢弃</button><button class="primary" onclick={()=>action('pending-approve')} disabled={busy||!selected.valid}>✓ 审批并写入知识库</button></div>{/if}</main></div></div></div>
