<script lang="ts">
  import { onMount } from 'svelte';
  import { loadDashboard, trainerAction, type Dashboard } from './gateway';
  let { onBack, onSettings, onConnections, onChanged } = $props<{onBack:()=>void;onSettings:()=>void;onConnections:()=>void;onChanged:(profile:{name:string;bio:string;avatar:string})=>void}>();
  let data=$state<Dashboard|null>(null); let busy=$state(false); let error=$state(''); let editing=$state(false);
  let name=$state('学习者'); let bio=$state(''); let avatar=$state('🧑‍💻');
  async function refresh(){busy=true;error='';try{data=await loadDashboard();name=data.profile.name;bio=data.profile.bio;avatar=data.profile.avatar;}catch(e){error=e instanceof Error?e.message:String(e)}finally{busy=false}}
  async function save(){busy=true;error='';try{await trainerAction('profile-save',{id:'local',name:name.trim()||'学习者',bio:bio.trim(),avatar});editing=false;onChanged({name,bio,avatar});await refresh()}catch(e){error=e instanceof Error?e.message:String(e)}finally{busy=false}}
  function intensity(count:number){return count===0?0:Math.min(4,1+Math.floor(Math.log2(count)))}
  function radarPoints(langs:Dashboard['languages'], github=false){const top=langs.slice(0,8);if(top.length<3)return'';const max=Math.max(1,...top.map(x=>x.githubBytes));return top.map((x,i)=>{const a=-Math.PI/2+i*2*Math.PI/top.length;const value=github?(x.githubBytes?Math.max(.1,Math.sqrt(x.githubBytes/max)):0):(x.score??0)/100;const r=72*value;return `${100+Math.cos(a)*r},${100+Math.sin(a)*r}`}).join(' ')}
  onMount(refresh);
</script>
<div class="profile-page">
  <header class="profile-toolbar"><button class="plain" onclick={onBack}>‹ 返回课程</button><strong>学习档案</strong><span></span><button class="chip" onclick={onConnections}>● VS Code · 连接管理</button><button class="chip">⌁ GitHub {data?.github?'已连接':'未连接'}</button><button class="icon-button" onclick={onSettings}>⚙</button><button class="icon-button" onclick={refresh} disabled={busy}>↻</button></header>
  <div class="profile-scroll"><div class="profile-content">
    <section class="profile-hero"><button class="hero-menu" onclick={()=>editing=!editing}>•••</button><div class="identity"><span class="avatar large">{avatar}</span><div><h1>{name}</h1><p>{bio||'保持好奇，持续生长。'}</p></div><span class="privacy">♢</span></div></section>
    {#if editing}<section class="glass-card profile-editor"><label>头像<input bind:value={avatar} maxlength="12"/></label><label>名称<input bind:value={name} maxlength="60"/></label><label>简介<input bind:value={bio} maxlength="160"/></label><div><button class="primary" onclick={save} disabled={busy}>保存资料</button><button class="secondary" onclick={()=>editing=false}>取消</button></div></section>{/if}
    {#if error}<div class="notice">{error}</div>{/if}
    {#if busy&&!data}<div class="dashboard-grid">{#each [1,2,3,4] as _}<div class="glass-card skeleton"></div>{/each}</div>
    {:else if data}
      <div class="summary-grid"><section class="glass-card metric"><span>◈ 学习等级</span><strong>Lv. {data.level??1}</strong><p>{data.xp??0} XP · 持续积累</p></section><section class="glass-card metric"><span>✓ 课堂凭据</span><strong>{data.evidenceCount}</strong><p>{data.conceptCount??0} 个知识点</p></section><section class="glass-card metric"><span>⌁ 活跃天数</span><strong>{data.activeDays}</strong><p>最长连续 {data.longestStreak??0} 天</p></section><section class="glass-card metric"><span>↗ 当前连续</span><strong>{data.currentStreak} 天</strong><p>今天也留下学习证据</p></section></div>
      <section class="glass-card activity-card"><div class="card-heading"><h2>▦ 学习活动</h2><div class="segmented mini"><button class="active">每日</button><button>每周</button><button>累计</button></div></div><div class="heatmap">{#each data.activity??[] as day}<span class="heat-{intensity(day.count)}" title={`${day.day} · ${day.count}`}></span>{/each}</div><p class="legend">过去 365 天 · 凭据数量 <span>少</span><i class="heat-1"></i><i class="heat-2"></i><i class="heat-3"></i><i class="heat-4"></i><span>多</span></p></section>
      <div class="dashboard-split"><section class="glass-card radar-card"><h2>⬡ 语言能力与 GitHub 项目信号</h2>{#if data.languages.length>=3}<svg class="radar" viewBox="0 0 200 220" aria-label="能力雷达图"><g class="radar-grid"><circle cx="100" cy="100" r="72"/><circle cx="100" cy="100" r="54"/><circle cx="100" cy="100" r="36"/><circle cx="100" cy="100" r="18"/></g><polygon class="github-polygon" points={radarPoints(data.languages,true)}/><polygon class="score-polygon" points={radarPoints(data.languages)}/>{#each data.languages.slice(0,8) as language,i}<text x={100+Math.cos(-Math.PI/2+i*2*Math.PI/Math.min(8,data.languages.length))*90} y={104+Math.sin(-Math.PI/2+i*2*Math.PI/Math.min(8,data.languages.length))*90}>{language.name}</text>{/each}</svg>{:else}<div class="empty-compact">完成课程或同步 GitHub 后生成雷达图</div>{/if}<div class="legend-lines"><span class="cyan">━ 实线 · 课堂 AI 评估</span><span class="orange">┄ 虚线 · GitHub 项目信号</span></div></section>
      <section class="glass-card language-archive"><div class="card-heading"><h2>⌘ 语言能力档案</h2><span>{data.languages.length} 种语言</span></div><div class="language-list">{#each data.languages as language}<article><div><strong>{language.name}</strong><span>{language.score==null?'未评估':`${language.score} / 100`}</span></div>{#if language.score!=null}<progress max="100" value={language.score}></progress>{/if}<small>{language.evidenceCount} 条课堂凭据</small><small class="github">{language.githubBytes?`GitHub · ${language.githubRepositoryCount} 个项目 · ${Math.ceil(language.githubBytes/1024)} KB`:'暂无 GitHub 数据'}</small></article>{/each}</div></section></div>
      <section class="glass-card recent-card"><h2>▤ 最近学习凭据</h2>{#each data.recent??[] as record}<div class="record"><span>✓</span><p>{record.note}<small>{record.concept_id}</small></p><time>{record.created_at.slice(0,10)}</time></div>{:else}<p class="muted">还没有记录。在课程中提交回答后，这里会显示学习足迹。</p>{/each}</section>
    {/if}
  </div></div>
</div>
